apiVersion: v1
kind: ServiceAccount
metadata:
  name: eks-admission-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "eks-admission.labels" . | indent 4 }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eks-admission-{{ .Release.Name }}
  labels:
{{ include "eks-admission.labels" . | indent 4 }}
rules:
  - apiGroups: [ "" ]
    resources: [ "pods", "pods/status", "configmaps" ]
    verbs: [ "get", "list", "update", "patch", "watch", "delete", "create" ]
  - apiGroups: [ "" ]
    resources: [ "services", "nodes", "replicationcontrollers", "persistentvolumeclaims", "persistentvolumes" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "" ]
    resources: [ "events" ]
    verbs: [ "create", "patch" ]
  - apiGroups: [ "storage.k8s.io" ]
    resources: [ "storageclasses" ]
    verbs: [ "list","get","watch" ]
  - apiGroups: [ "apps" ]
    resources: [ "replicasets", "statefulsets" ]
    verbs: [ "list", "get", "watch" ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eks-admission-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "eks-admission.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: eks-admission-{{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: eks-admission-{{ .Release.Name }}
    namespace: {{ .Release.Namespace }}