# Default values for tapm-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: ccr.ccs.tencentyun.com/tke-market/tapm-operator
  pullPolicy: IfNotPresent
  tag: latest

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

env:
  CLUSTER_ID: ""
  TKE_REGION: ""
  APM_TOKEN: ""
