apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tapm-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tapm-operator-manager-role
subjects:
- kind: ServiceAccount
  name: tapm-operator-controller-manager
  namespace: tapm-operator-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tapm-operator-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tapm-operator-proxy-role
subjects:
- kind: ServiceAccount
  name: tapm-operator-controller-manager
  namespace: tapm-operator-system
