apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: tapm-operator-system/tapm-operator-serving-cert
  name: tapm-operator-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: tapm-operator-webhook-service
      namespace: tapm-operator-system
      path: /validate-operator-skywalking-apache-org-v1alpha1-javaagent
  failurePolicy: Fail
  name: vjavaagent.kb.io
  rules:
  - apiGroups:
    - operator.skywalking.apache.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - javaagents
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: tapm-operator-webhook-service
      namespace: tapm-operator-system
      path: /validate-operator-skywalking-apache-org-v1alpha1-swagent
  failurePolicy: Fail
  name: vswagent.kb.io
  rules:
  - apiGroups:
    - operator.skywalking.apache.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - swagents
  sideEffects: None
