---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eklet-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "eklet.labels" . | indent 4 }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eklet-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "eklet.labels" . | indent 4 }}
rules:
  - apiGroups: [ "" ]
    resources: [ "nodes", "nodes/status", "services", "namespaces", "secrets" ]
    verbs: [ "get", "list", "patch", "update", "watch" ]
  - apiGroups: [ "" ]
    resources: [ "events", "endpoints", "configmaps" ]
    verbs: [ "create", "get","list","patch", "update", "watch" ]
  - apiGroups: [ "" ]
    resources: [ "pods", "bindings", "pods/binding", "pods/status", "configmaps" ]
    verbs: [ "delete", "update", "patch", "get", "list", "watch" ]
  - apiGroups: [ "" ]
    resources: [ "events", "endpoints", "endpointslices", "configmaps", "serviceaccounts/token", "persistentvolumeclaims", "persistentvolumes", "services/proxy" ]
    verbs: [ "create", "get","list","patch", "update", "watch" ]
  - apiGroups: [ "batch" ]
    resources: [ "jobs" ]
    verbs: [ "create", "get","list","patch", "update", "watch" ]
  - apiGroups: [ "storage.k8s.io" ]
    resources: [ "csinodes" ]
    verbs: [ "create", "get","list","patch", "update", "watch" ]
  - apiGroups: [ "" ]
    resources: [ "pods/status" ]
    verbs: [ "get", "list", "patch", "update", "watch" ]
  - apiGroups: [ "coordination.k8s.io" ]
    resources: [ "leases" ]
    verbs: [ "create", "get", "list", "patch", "update","watch" ]
  - apiGroups: [ "authorization.k8s.io" ]
    resources: [ "subjectaccessreviews" ]
    verbs: [ "create", "get", "list", "patch", "update", "watch" ]
  - apiGroups: [ "authentication.k8s.io" ]
    resources: [ "tokenreviews" ]
    verbs: [ "create" ]
  - apiGroups: [ "cls.cloud.tencent.com" ]
    resources: [ "logconfigs" ]
    verbs:  [ "create", "get", "list", "patch", "update","watch" ]
  - apiGroups: [ "apps" ]
    resources: [ "replicasets", "statefulsets" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "extensions" ]
    resources: [ "replicasets" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "policy" ]
    resources: [ "poddisruptionbudgets" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "authentication.k8s.io" ]
    resources: [ "tokenreviews" ]
    verbs: [ "create" ]
  - apiGroups: [ "authorization.k8s.io" ]
    resources: [ "subjectaccessreviews" ]
    verbs: [ "create" ]
    
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eklet-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "eklet.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: eklet-{{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: eklet-{{ .Release.Name }}
    namespace: {{ .Release.Namespace }}