apiVersion: v1
kind: ServiceAccount
metadata:
  name: eks-admission-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "eks-admission.labels" . | indent 4 }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eks-admission-{{ .Release.Name }}
  labels:
{{ include "eks-admission.labels" . | indent 4 }}
rules:
  - apiGroups: [ "" ]
    resources: [ "configmaps", "nodes", "replicationcontrollers", "services", "persistentvolumeclaims", "persistentvolumes" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "" ]
    resources: [ "pods", "bindings", "pods/binding", "pods/status", "configmaps" ]
    verbs: [ "get", "list", "watch", "delete", "create", "update", "patch" ]
  - apiGroups: [ "" ]
    resources: [ "events", "services/proxy" ]
    verbs: [ "create", "patch", "update"]
  - apiGroups: [ "coordination.k8s.io" ]
    resources: [ "leases" ]
    verbs: [ "create" ]
  - apiGroups: [ "coordination.k8s.io" ]
    resourceNames: [ "tke-scheduler" ]
    resources: [ "leases" ]
    verbs: [ "get", "update" ]
  - apiGroups: [ "" ]
    resourceNames: ["tke-scheduler" ]
    resources: [ "endpoints" ]
    verbs: [ "delete", "patch", "get", "update" ]
  - apiGroups: [ "events.k8s.io" ]
    resources: [ "events" ]
    verbs: [ "create", "patch", "update"]
  - apiGroups: [ "apps" ]
    resources: [ "replicasets", "statefulsets" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "extensions" ]
    resources: [ "replicasets" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "policy" ]
    resources: [ "poddisruptionbudgets" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "authentication.k8s.io" ]
    resources: [ "tokenreviews" ]
    verbs: [ "create" ]
  - apiGroups: [ "authorization.k8s.io" ]
    resources: [ "subjectaccessreviews" ]
    verbs: [ "create" ]
  - apiGroups: [ "storage.k8s.io" ]
    resources: [ "csinodes" ]
    verbs: [ "get", "list", "watch" ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eks-admission-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "eks-admission.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: eks-admission-{{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: eks-admission-{{ .Release.Name }}
    namespace: {{ .Release.Namespace }}