apiVersion: v1
kind: ConfigMap
metadata:
  name: eks-config
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "eks-admission.labels" . | indent 4 }}
data:
  AUTO_SCALE_EKS: {{ .Values.eksAdmission.autoScaleEKS }}
