{{- range .Values.cloud.subnets }}
apiVersion: v1
kind: Node
metadata:
  annotations:
    eks.tke.cloud.tencent.com/subnet-id: {{ .id }}
  labels:
{{ include "node.labels" . | indent 4 }}
  name: eklet-{{ .id }}
spec:
  taints:
  - effect: NoSchedule
    key: eks.tke.cloud.tencent.com/eklet
---
{{- end }}
