{{- if (.Values.hook.serviceAccount.create) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "hookServiceAccount" . }}
  namespace: "{{.Release.Namespace}}"
  annotations:
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook": "post-delete"
  labels:
    app.kubernetes.io/managed-by: {{.Release.Service | quote }}
    app.kubernetes.io/instance: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
---
kind: ClusterRole
apiVersion: {{ .Values.rbacGroup }}/v1
metadata:
  annotations:
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook": "post-delete"
  name: {{ template "hookServiceAccount" . }}
rules:
  - apiGroups: ["apiregistration.k8s.io"]
    resources: ["apiservices"]
    verbs: ["delete"]
---
kind: ClusterRoleBinding
apiVersion: {{ .Values.rbacGroup }}/v1
metadata:
  annotations:
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook": "post-delete"
  name: {{ template "hookServiceAccount" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "hookServiceAccount" . }}
    namespace: "{{.Release.Namespace}}"
roleRef:
  kind: ClusterRole
  name: {{ template "hookServiceAccount" . }}
  apiGroup: {{ .Values.rbacGroup }}
{{- end }}
