apiVersion: batch/v1
kind: Job
metadata:
  name: "{{.Release.Name}}"
  labels:
    app.kubernetes.io/managed-by: {{.Release.Service | quote}}
    app.kubernetes.io/instance: {{.Release.Name | quote}}
    helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: "{{.Release.Name}}"
      labels:
        app.kubernetes.io/managed-by: {{.Release.Service | quote}}
        app.kubernetes.io/instance: {{.Release.Name | quote}}
        helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
      restartPolicy: Never
      serviceAccountName: {{ template "hookServiceAccount" . }}
      containers:
      - name: "{{.Release.Name}}-post-delete-job"
        image: {{ .Values.hook.image.ref }}
        imagePullPolicy: {{ .Values.hook.image.pullPolicy }}
        args: ["delete", "apiservice", "v1.packages.operators.coreos.com", "--ignore-not-found"]
