apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mpi-operator.fullname" . }}
  namespace: {{ include "mpi-operator.namespaceName" . }}
  labels:
    {{- include "mpi-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mpi-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mpi-operator.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "mpi-operator.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["{{ .Values.command }}"]
          args: [
              "-alsologtostderr",
              "{{ .Values.args.optionKubectlDeliverImage }}",
              "{{ .Values.args.kubectlDeliverImage }}"
          ]
          imagePullPolicy: {{ .Values.image.pullPolicy }}
