{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mpi-operator.serviceAccountName" . }}
  namespace: {{ include "mpi-operator.namespaceName" . }}
{{- end }}
