kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "mpi-operator.name" . }}
  namespace: {{ include "mpi-operator.namespaceName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "mpi-operator.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "mpi-operator.serviceAccountName" . }}
    namespace: {{ include "mpi-operator.namespaceName" . }}
