---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ include "pytorch-operator.name" . }}
  namespace: {{ include "pytorch-operator.namespaceName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "pytorch-operator.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "pytorch-operator.serviceAccountName" . }}
  namespace: {{ include "pytorch-operator.namespaceName" . }}
