apiVersion: v2
name: bigdl-trusted-fl
description: BigDL Privacy Preserving Machine Learning (PPML) for FL based on Intel SGX
type: application
version: 0.1.0
appVersion: 2.1.0-SNAPSHOT
icon: https://imgcache.qq.com/qcloud/tcloud_dtc/static/Industry_tke/01e39f9b-ee73-41ad-8b49-1dd1730247af.jpg
keywords:
 - bigdl
maintainers:
 - name: Gong Qiyuan
   email: qiyuan.gong@intel.com
