apiVersion: v2
name: opentelemetry-operator
version: 0.39.0
description: OpenTelemetry Operator Helm chart for Kubernetes
type: application
home: https://opentelemetry.io/
sources:
  - https://github.com/open-telemetry/opentelemetry-operator
maintainers:
  - name: jeffreyhlhe
icon: https://cloudcache.tencent-cloud.com/qcloud/ui/static/Industry_tke/80444e53-c142-4896-bc8a-ef4ecf75c682.png
appVersion: 0.85.0
kubeVersion: '>= 1.19.0-0, <= 1.28.0-0 '


