apiVersion: v2
name: bigdl-trusted-realtime-ml
description: A Helm chart for bigdl-trusted-realtime-ml
type: application
version: 0.1.0
icon: https://imgcache.qq.com/qcloud/tcloud_dtc/static/Industry_tke/01e39f9b-ee73-41ad-8b49-1dd1730247af.jpg
appVersion: "2.1.0-SNAPSHOT"
keywords:
 - bigdl
maintainers:
 - name: glorysdj
   email: dongjie.shi@intel.com
