image: ccr.ccs.tencentyun.com/tke-market/bigdl-ppml-trusted-big-data-ml-python-graphene:2.1.0-SNAPSHOT
k8sMaster: k8s://https://master_ip:master_port
pvc: your_pvc

deployMode: client
driverCores: "1"
driverMem: "1g"
executorCores: "8"
executorMem: "1g"
executorInstances: "2"
sgx: "true"
sgxLog: "error"
sgxDriverMem: "32g"
sgxDriverJvmMem: "8g"
sgxExecutorMem: "32g"
sgxExecutorJvmMem: "12g"
