apiVersion: v1
appVersion: 1.0.3
description: BigData Suit on K8s, HDFS/Hive/Kudu/Impala/Spark/Flink ...
home: https://github.com/tkestack/charts
icon: https://imgcache.qq.com/qcloud/tcloud_dtc/static/Industry_tke/b1f4a8cb-664b-4ef2-9f4b-7327a1969ec5.jpg
keywords:
- spark
- hdfs
- hive
- kudu
- impala
- flink
- prometheus
- grafana
- superset
maintainers:
- email: timxbxu@tencent.com
  name: timxbxu
- email: kangtian@tencent.com
  name: kangtian
- email: toringzhang@tencent.com
  name: toringzhang
name: k8s-big-data-suite
version: 1.0.3
kubeVersion: <= 1.16.3-x
