apiVersion: v2
name: tke-autoscaling-placeholder
version: 1.0.0
description: Autoscaling placeholder for TKE.
type: application
keywords:
- tke
- autoscaling
- placeholder
home: https://github.com/tkestack/charts
appVersion: 1.0.0
maintainers:
- name: roc
  email: rockerchen@gmail.com
  url: https://imroc.io
icon: https://imgcache.qq.com/qcloud/tcloud_dtc/static/Industry_tke/1676653d-8f85-41df-b698-01771ae7ee01.png
kubeVersion: <= 1.22.5-x
