apiVersion: v1
appVersion: "3.3"
description: Lightning-fast, distributed SQL queries for petabytes of data stored in Apache Hadoop clusters.
home: https://github.com/apache/impala
name: impala
sources:
- https://github.com/apache/impala
version: 1.0.0
