apiVersion: v1
kind: Service
metadata:
  name: {{ include "pytorch-operator.fullname" . }}
  namespace: {{ include "pytorch-operator.namespaceName" . }}
  labels:
    {{- include "pytorch-operator.labels" . | nindent 4 }}
  annotations:
    {{- include "pytorch-operator.serviceAnnotations" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      name: {{ .Values.service.name }}
  selector:
    {{- include "pytorch-operator.selectorLabels" . | nindent 4 }}
