{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pytorch-operator.serviceAccountName" . }}
  namespace: {{ include "pytorch-operator.namespaceName" . }}
{{- end }}
