apiVersion: {{ .Values.rbacGroup }}/v1
kind: ClusterRole
metadata:
  name: system:controller:operator-lifecycle-manager
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
- nonResourceURLs: ["*"]
  verbs: ["*"]
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ template "olmServiceAccount" . }}
  namespace: {{ .Values.olm_namespace }}
---
apiVersion: {{ .Values.rbacGroup }}/v1
kind: ClusterRoleBinding
metadata:
  name: olm-operator-binding-{{ .Values.olm_namespace }}
roleRef:
  apiGroup: {{ .Values.rbacGroup }}
  kind: ClusterRole
  name: system:controller:operator-lifecycle-manager
subjects:
- kind: ServiceAccount
  name: {{ template "olmServiceAccount" . }}
  namespace: {{ .Values.olm_namespace }}
