apiVersion: v1
kind: ServiceAccount
metadata:
  name: enterprise-gateway-sa
  namespace: {{ include "elastic-jupyter-operator.namespaceName" . }}
  labels:
    app: enterprise-gateway
    component: enterprise-gateway
