# This is a basic workflow to help you get started with Actions

name: Lint and Test Charts

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name:  Helm charts lint
        uses:  rootdeep/helm-gh-pages@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          helm_version: 3.5.2
          charts_dir: incubator
